// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PracticaFinalWebApi.Data;

namespace PracticaFinalWebApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210712184534_ParteDos")]
    partial class ParteDos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("PracticaFinalWebApi.Models.Auto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("money");

                    b.HasKey("Id");

                    b.ToTable("Vehiculo");
                });

            modelBuilder.Entity("PracticaFinalWebApi.Models.Empleado", b =>
                {
                    b.Property<int>("CodEmpleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Empleados")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Oficina")
                        .HasColumnType("int");

                    b.Property<decimal>("Salario")
                        .HasColumnType("money");

                    b.HasKey("CodEmpleado");

                    b.HasIndex("Empleados");

                    b.HasIndex("Oficina");

                    b.ToTable("Empleado");
                });

            modelBuilder.Entity("PracticaFinalWebApi.Models.Oficina", b =>
                {
                    b.Property<int>("CodOficina")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Direccion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Localidad")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Provincia")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("CodOficina");

                    b.ToTable("Oficina");
                });

            modelBuilder.Entity("PracticaFinalWebApi.Models.Reserva", b =>
                {
                    b.Property<int>("CodReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Destino")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Empleado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<double>("Kilometros")
                        .HasColumnType("float");

                    b.Property<int?>("Reservas")
                        .HasColumnType("int");

                    b.Property<int>("Vehiculo")
                        .HasColumnType("int");

                    b.HasKey("CodReserva");

                    b.HasIndex("Empleado");

                    b.HasIndex("Reservas");

                    b.HasIndex("Vehiculo");

                    b.ToTable("Reserva");
                });

            modelBuilder.Entity("PracticaFinalWebApi.Models.Empleado", b =>
                {
                    b.HasOne("PracticaFinalWebApi.Models.Oficina", null)
                        .WithMany("Empleados")
                        .HasForeignKey("Empleados");

                    b.HasOne("PracticaFinalWebApi.Models.Oficina", "CodOficina")
                        .WithMany()
                        .HasForeignKey("Oficina")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CodOficina");
                });

            modelBuilder.Entity("PracticaFinalWebApi.Models.Reserva", b =>
                {
                    b.HasOne("PracticaFinalWebApi.Models.Empleado", "CodEmpleado")
                        .WithMany()
                        .HasForeignKey("Empleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PracticaFinalWebApi.Models.Empleado", null)
                        .WithMany("Reservas")
                        .HasForeignKey("Reservas");

                    b.HasOne("PracticaFinalWebApi.Models.Auto", null)
                        .WithMany("Reservas")
                        .HasForeignKey("Reservas");

                    b.HasOne("PracticaFinalWebApi.Models.Auto", "CodVehiculo")
                        .WithMany()
                        .HasForeignKey("Vehiculo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CodEmpleado");

                    b.Navigation("CodVehiculo");
                });

            modelBuilder.Entity("PracticaFinalWebApi.Models.Auto", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("PracticaFinalWebApi.Models.Empleado", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("PracticaFinalWebApi.Models.Oficina", b =>
                {
                    b.Navigation("Empleados");
                });
#pragma warning restore 612, 618
        }
    }
}
